### PR TITLE
Fixed a few issues on Android + added tests

### LINKED ISSUE #18: Not closed a PDF documents warnings on Android
Here's a message I got after extracting text from a PDF file on Android
`W/PdfBox-Android(10576):` Warning: You did not close a PDF Document`

### LINKED ISSUE #19: PDFDoc.text is not re-entrant
It is not safe to call the PDFDoc.text multiple times in succession, meaning to call it again before the previous call returns. 
I's a pretty common scenario when an app may be processing more than one pdf file at a time.
If the program enters this function more than once before the previous call returns the app will crash. 
I have tested this on a real Android device only and it crashes every single time if multiple pdfs are processed. Not sure how it behaves on iOS though.

There seems to be a workaround and it could be outlined as follows:

class PDFReader{

  static final _lock = Lock();

...
 
  Future<String> pdfToString(File aPdfFile) async {
  ...
    String result;
    PDFDoc doc = await PDFDoc.fromFile(aPdfFile);
    await _lock.synchronized(() async {
        result = await doc.text;
    });
  ...
    return result;
  }
...

}

Where the Lock comes from https://pub.dev/packages/synchronized

### PR DESCRIPTION
**Pull request by hicnar**
To find out what has been changed please look at the commit comments.
This PR should be followed by the removal of the fastInit option in the external API.
fixes #19
fixes #18

### CODE REVIEW

**Comment by AlessioLuciani** [comment]
@hicnar thank you for the contribution! I will look at it as soon as I can.

File: android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt [hunk 1]
```diff
@@ -1,44 +1,31 @@
...
-  private var pdfTextStripper = PDFTextStripper()
+class PdfTextPlugin: FlutterPlugin, MethodCallHandler {
 
+  @Suppress("DEPRECATION")
   override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
-    val channel = MethodChannel(flutterPluginBinding.getFlutterEngine().getDartExecutor(), "pdf_text")
-    channel.setMethodCallHandler(PdfTextPlugin());
+    val channel = MethodChannel(flutterPluginBinding.flutterEngine.dartExecutor, "pdf_text")
+    channel.setMethodCallHandler(PdfTextPlugin())
+    PDFBoxResourceLoader.init(flutterPluginBinding.applicationContext)
```
Comment (AlessioLuciani) [inline android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt:25]: Great! So does this essentially load the resources immediately?

File: android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt [hunk 2]
```diff
@@ -1,44 +1,31 @@
...
-  private var cachedDoc: PDDocument? = null
-  private var cachedDocPath: String? = null
-
-  /**
-   * PDF text stripper.
-   */
-  private var pdfTextStripper = PDFTextStripper()
+class PdfTextPlugin: FlutterPlugin, MethodCallHandler {
 
+  @Suppress("DEPRECATION")
```
Comment (AlessioLuciani) [inline android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt]: What does this deprecation refer to?

File: android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt [hunk 3]
```diff
@@ -53,18 +40,19 @@ public class PdfTextPlugin: FlutterPlugin, MethodCallHandler {
     fun registerWith(registrar: Registrar) {
       val channel = MethodChannel(registrar.messenger(), "pdf_text")
       channel.setMethodCallHandler(PdfTextPlugin())
+      PDFBoxResourceLoader.init(registrar.context())
     }
   }
 
+  @Suppress("UNCHECKED_CAST")
```
Comment (AlessioLuciani) [inline android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt]: Maybe here we can check or force the cast instead of suppressing the warning.

File: example/test/pdf_text_test.dart [hunk 4]
```diff
@@ -0,0 +1,128 @@
+@Skip('To run these tests, make sure an emulator or a real device is connected, then \'cd example\' and : \'flutter test/pfd_text_test.dart\'')
```
Comment (AlessioLuciani) [inline example/test/pdf_text_test.dart]: Are you sure that it can be launched with this command? Shouldn't "flutter" be followed by a command? I could not run the tests :( .
Great job by the way! Can't wait to see it running.

File: lib/pdf_text.dart [hunk 5]
```diff
@@ -120,9 +121,12 @@ class PDFDoc {
...
     }
-    String text = "";
-    _pages.forEach((page) => text += "${page._text}\n");
-    return text;
+    /// Removed the \n added at the end of each page here (potentially a breaking change!).
+    /// Since every page can be retrieved individually, the client knows exactly
+    /// where it begins and where it ends, therefore there is no benefit of
+    /// introducing an artificial page separator that is not part of the pdf
+    /// document per se
+    return _pages.fold<String>("", (pv, page) => "$pv${page._text}");
```
Comment (AlessioLuciani) [inline lib/pdf_text.dart:132]: Yes, removing the "\n" makes sense. Starting the fold with "" means preceding the entire text with a "", right?

**Review by AlessioLuciani — CHANGES_REQUESTED** [review]

File: android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt (hunk 1 above)
Comment (hicnar) [reply android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt:25]: Yes. And it improved the performance on Android quite a bit!

File: android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt (hunk 2 above)
Comment (hicnar) [reply android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt]: In the ```flutterPluginBinding.flutterEngine.dartExecutor``` fragment, the ```flutterEngine``` is deprecated, but I could not figure out a way to get the ```dartExecutor``` other than by doing the above

File: lib/pdf_text.dart (hunk 5 above)
Comment (hicnar) [reply lib/pdf_text.dart:132]: That means that the fold will start concatenating to an empty string, so essentially yes the entire text will start with an empty string.

File: example/test/pdf_text_test.dart (hunk 4 above)
Comment (hicnar) [reply example/test/pdf_text_test.dart]: Woopsie, my bad! Absolutely you can run the tests like that! I have just somehow.. forgotten to add the 'run', so it is
```flutter run test/pdf_text_test.dart``` invoked from the example directory

File: android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt (hunk 3 above)
Comment (hicnar) [reply android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt]: Changed, now the unchecked_cast applies only to the ```as List<Int>``` and I'm not sure there's anything more that can be done when it comes to casting generics

File: android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt (hunk 1 above)
Comment (hicnar) [reply android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt:25]: One more note here. It seems to be working fine for both pre-flutter 1.12 and post as I migrated my project literally as I was working on this stuff. It worked prior to the migration and it continuous to work now.

File: example/test/pdf_text_test.dart (hunk 4 above)
Comment (hicnar) [reply example/test/pdf_text_test.dart]: Added tests for password protected pdfs. The iOS part does not work (and I haven't touched it)

File: android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt (hunk 1 above)
Comment (AlessioLuciani) [reply android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt:25]: Perfect!

File: android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt (hunk 2 above)
Comment (AlessioLuciani) [reply android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt]: Ok, let's let it like this for now.

File: example/test/pdf_text_test.dart (hunk 4 above)
Comment (AlessioLuciani) [reply example/test/pdf_text_test.dart]: Awesome, I could run the tests! Weird situation on iOS, password protected files still work for me using the example app.

File: android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt (hunk 2 above)
Comment (AlessioLuciani) [reply android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt]: Nevermind, I guess we can replace that instruction with `channel = MethodChannel(flutterPluginBinding.getBinaryMessenger(), "pdf_text")` .
This should solve the problem and we can remove the suppression.
[Found here](https://stackoverflow.com/questions/61637647/flutterpluginbinding-flutterengine-is-deprecated).
@hicnar after this I think that we can merge this :D

Comment (hicnar) [reply android/src/main/kotlin/dev/aluc/pdf_text/PdfTextPlugin.kt]: Great find! All done now

**Review by AlessioLuciani — APPROVED** [review]

File: example/test/pdf_text_test.dart (hunk 4 above)
Comment (hicnar) [reply example/test/pdf_text_test.dart]: @AlessioLuciani Though it should not be the case, but perhaps it is related to the way the pdf is created? I created the one the tests are run against by simply exporting it from a LibreOffice Write document on Mac. If you could create a password protected pdf (with the password = password), confirm it works in the example app when run on iOS, then just stick it in the test/resources next to the one I created, we could modify the tests to point to the one that we know works in the example app and possibly figure out what the problem is?

Comment (AlessioLuciani) [reply example/test/pdf_text_test.dart]: @hicnar now I have had a chance to try the test on iOS too (previously I had issues with running the iOS emulator and I only could on Android). I removed the if condition that stops the test for encrypted documents on iOS and run the test with your document, it seems to work for me! It does not prompt any errors and says that all tests passed. So I guess this is good news. Maybe is it that the problem is only on your emulator?

Comment (hicnar) [reply example/test/pdf_text_test.dart]: @AlessioLuciani That's really interesting! So I understand you tried to run the tests against a real device?

Comment (AlessioLuciani) [reply example/test/pdf_text_test.dart]: @hicnar no, what I described happened on my iOS emulator.
